# Generated by Django 5.0.6 on 2024-07-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft",
            name="name",
            field=models.CharField(default="aircraft_default_name", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="airline",
            name="name",
            field=models.CharField(default="airline_default", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="airlineticket",
            name="name",
            field=models.CharField(default="airline_ticket_name", max_length=50),
            preserve_default=False,
        ),
    ]
