# Generated by Django 5.0.7 on 2024-07-28 07:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airline_tickets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerticket",
            name="aircraft_seat",
        ),
        migrations.RemoveField(
            model_name="customerticket",
            name="customer",
        ),
        migrations.AddField(
            model_name="customerticket",
            name="customer_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="FlightSeat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "aircraft_seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="airline_tickets.aircraftseat",
                    ),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="airline_tickets.flight",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="customerticket",
            name="flight_seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="airline_tickets.flightseat",
            ),
        ),
    ]
