# Generated by Django 5.0.7 on 2024-07-28 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airline_tickets", "0002_remove_customerticket_aircraft_seat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="airline_tickets.airlinecompany",
            ),
        ),
    ]
