# Generated by Django 5.0.6 on 2024-07-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airline_tickets", "0003_alter_flightroute_waypoints"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airlineticket",
            name="airline_seat_type",
        ),
        migrations.DeleteModel(
            name="FlightSeatType",
        ),
        migrations.DeleteModel(
            name="AirlineSeatType",
        ),
    ]
