# Generated by Django 5.0.6 on 2024-07-21 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_tickets", "0004_remove_airlineticket_airline_seat_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AirlineTicketType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="airlineticket",
            name="airline_ticket_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="airline_tickets.airlinetickettype",
            ),
        ),
    ]
