# Generated by Django 5.0.7 on 2024-07-28 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airline_tickets", "0004_rename_company_flight_airline_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="airline_company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="airline_tickets.airlinecompany",
            ),
        ),
    ]
