# Generated by Django 5.0.7 on 2024-07-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airline_tickets", "0005_alter_flight_airline_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightseat",
            name="reserved",
            field=models.BooleanField(default=False),
        ),
    ]
