# Generated by Django 5.0.7 on 2024-07-29 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airline_tickets", "0007_flightseat_unique_flight_aircraft_seat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flightseat",
            name="reserved",
        ),
    ]
