# Generated by Django 5.0.6 on 2024-07-21 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airline_tickets", "0007_aircraftseat_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flight",
            old_name="date",
            new_name="publish_date",
        ),
    ]
