# Generated by Django 5.0.7 on 2024-07-30 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airline_tickets", "0009_remove_airlineticket_airline_ticket_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airlineticket",
            name="aircraft_seat_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="airline_tickets.aircraftseattype",
            ),
        ),
    ]
