# Generated by Django 5.0.6 on 2024-07-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_tickets", "0010_alter_address_id_alter_aircraft_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airport",
            name="iata_code",
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name="airport",
            name="icao_code",
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
