# Generated by Django 5.0.7 on 2024-07-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_tickets", "0010_alter_airlineticket_aircraft_seat_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerticket",
            name="canceled",
            field=models.BooleanField(default=False),
        ),
    ]
